
obj-y	+=  lgtp_common_driver.o
obj-y	+=  lgtp_platform_api.o
obj-y	+=  lgtp_model_config.o

ifeq ($(CONFIG_MSM8909_M1), y)
obj-y   += MIT200_proc4/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MIT300), y)
obj-y   += MIT300/
endif
