
ifeq ($(CONFIG_TOUCHSCREEN_UNIFIED), y)
obj-y  += ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_MSM8916_YG), y)
obj-y   += ver_2_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_UNIFIED_V3), y)
obj-y	+= ver_3_0/
endif

ifeq ($(CONFIG_TOUCHSCREEN_UNIFIED_V4), y)
obj-y	+= ver_4_0/
endif
